# NYC Collision Analysis: Datalake & Athena Setup
This notebook sets up the foundational infrastructure on AWS. We're moving our local data into S3 and registering it with Athena so we can run SQL queries on the full dataset.

In [1]:
!pip install "sagemaker<3.0.0" awswrangler

import boto3
import sagemaker
import pandas as pd
import awswrangler as wr
import os

# 1. Connections
sess = sagemaker.Session()
bucket = sess.default_bucket()
region = sess.boto_region_name
prefix = "aai-540-group6/nyc-collisions"

s3_path = f"s3://{bucket}/{prefix}/data/raw/"
print(f"Target Datalake location: {s3_path}")

Collecting sagemaker<3.0.0
  Using cached sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: awswrangler in /opt/conda/lib/python3.12/site-packages (3.16.0)
Collecting attrs<26,>=24 (from sagemaker<3.0.0)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: boto3<2.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (1.42.97)
Requirement already satisfied: cloudpickle>=2.2.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (3.1.2)
Requirement already satisfied: docker in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (7.1.0)
Requirement already satisfied: fastapi in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (0.136.1)
Requirement already satisfied: google-pasta in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (0.2.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (3.4.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (6.10.0)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (4.23.0)
Requirement already satisfied: numpy<3.0,>=1.26.4 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (1.26.4)
Requirement already satisfied: omegaconf<3,>=2.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (2.3.0)

Collecting packaging<25,>=23.0 (from sagemaker<3.0.0)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pandas>=2.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (2.3.3)
Collecting pathos (from sagemaker<3.0.0)
  Using cached pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (4.9.6)
Requirement already satisfied: protobuf<7.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (6.31.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (5.9.8)
Requirement already satisfied: pyyaml>=6.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (6.0.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (2.33.1)

Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3.0.0)
  Using cached sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: schema in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (0.7.7)
Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (1.0.1)
Requirement already satisfied: tblib<4,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (3.2.2)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (4.67.3)
Requirement already satisfied: urllib3<3.0.0,>=1.26.8 in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (1.26.20)
Requirement already satisfied: uvicorn in /opt/conda/lib/python3.12/site-packages (from sagemaker<3.0.0) (0.46.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.97 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3.0.0) (1.42.97)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3.0.0) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0,>=1.42.2->sagemaker<3.0.0) (0.16.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3.0.0) (2.9.0.post0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3.0.0) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3.0.0) (3.2.0)
Requirement already satisfied: typing-extensions<5,>=4.7.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker<3.0.0) (4.15.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker<3.0.0) (3.23.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf<3,>=2.2->sagemaker<3.0.0) (4.9.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.97->boto3<2.0,>=1.42.2->sagemaker<3.0.0) (1.17.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (2.13.3)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (4.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3.0.0) (2025.9.1)

Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3.0.0) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema->sagemaker<3.0.0) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (2.20.0)
Requirement already satisfied: pyarrow<24.0.0,>=8.0.0 in /opt/conda/lib/python3.12/site-packages (from awswrangler) (21.0.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from awswrangler) (82.0.1)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=2.3.0->sagemaker<3.0.0) (2026.2)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3.0.0) (0.1.2)

Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3.0.0) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests->sagemaker<3.0.0) (2026.4.22)
Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3.0.0) (1.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi->sagemaker<3.0.0) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.46.0->fastapi->sagemaker<3.0.0) (4.13.0)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3.0.0)
  Using cached ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: dill>=0.4.1 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3.0.0) (0.4.1)

Collecting pox>=0.3.7 (from pathos->sagemaker<3.0.0)
  Using cached pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: multiprocess>=0.70.19 in /opt/conda/lib/python3.12/site-packages (from pathos->sagemaker<3.0.0) (0.70.19)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3.0.0) (8.2.1)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn->sagemaker<3.0.0) (0.16.0)
Using cached sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)

Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Using cached pathos-0.3.5-py3-none-any.whl (82 kB)
Using cached pox-0.3.7-py3-none-any.whl (29 kB)
Using cached ppft-1.7.8-py3-none-any.whl (56 kB)

Installing collected packages: ppft, pox, packaging, attrs, pathos, sagemaker-core, sagemaker

  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0

  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]

  Attempting uninstall: sagemaker-core
    Found existing installation: sagemaker-core 2.10.0
   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]

    Uninstalling sagemaker-core-2.10.0:
      Successfully uninstalled sagemaker-core-2.10.0
   ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━ 3/7 [attrs]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━ 5/7 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 6/7 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [sagemaker]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.5.0 requires nvidia-ml-py3<8.0,>=7.352.0, which is not installed.
autogluon-timeseries 1.5.0 requires chronos-forecasting<2.4,>=2.2.2, which is not installed.
autogluon-timeseries 1.5.0 requires einops<1,>=0.7, which is not installed.
autogluon-timeseries 1.5.0 requires peft<0.18,>=0.13.0, which is not installed.
skops 0.14.0 requires prettytable>=3.9, which is not installed.
autogluon-multimodal 1.5.0 requires fsspec[http]<=2025.3, but you have fsspec 2026.3.0 which is incompatible.
sagemaker-mlops 1.10.0 requires sagemaker-core>=2.10.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-serve 1.10.0 requires sagemaker-core>=2.10.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
sagemaker-train 1.10.0 requires sagemaker-core>=2.10.0, but you have sagemaker-core 1.0.78 which is incompatible.
sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 2.3.3 which is incompatible.
Successfully installed attrs-25.4.0 packaging-24.2 pathos-0.3.5 pox-0.3.7 ppft-1.7.8 sagemaker-2.257.3 sagemaker-core-1.0.78

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml

sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

Target Datalake location: s3://sagemaker-us-east-1-016517410335/aai-540-group6/nyc-collisions/data/raw/

### Load the Merged Sample
We use the 1,000-row sample created in Phase 1 as our starting point.

In [2]:
csv_file = '../data/raw/merged_sample.csv'

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file, low_memory=False)
    print(f"Found sample data: {df.shape[0]} rows merged.")
else:
    print("Error: CSV missing. Run src/data_loader.py first.")

Found sample data: 50000 rows merged.

### Populate the Datalake
Push to S3 and sync the Glue Catalog (Athena) in one go.

In [3]:
db = 'nyc_collision_db'
table = 'merged_raw'

# Make sure DB exists
wr.catalog.create_database(db, exist_ok=True)

# Push data
wr.s3.to_csv(
    df=df,
    path=s3_path,
    dataset=True,
    database=db,
    table=table,
    index=False,
    mode='overwrite'
)

print(f"Database '{db}' updated. Table '{table}' ready for SQL.")

2026-06-16 04:33:04,974	WARNING services.py:2137 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 1908387840 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=4.52gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.

2026-06-16 04:33:05,122	INFO worker.py:2007 -- Started a local Ray instance.

/opt/conda/lib/python3.12/site-packages/ray/_private/worker.py:2046: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

Database 'nyc_collision_db' updated. Table 'merged_raw' ready for SQL.

### Quick SQL Check
Run some Athena queries to verify the ingestion.

In [4]:
# Check distributions across boroughs
q1 = f"SELECT borough, count(*) as total FROM {db}.{table} GROUP BY borough ORDER BY total DESC"
res1 = wr.athena.read_sql_query(q1, database=db)
display(res1)

         borough  total
0                 17291
1       BROOKLYN  11441
2         QUEENS   8729
3          BRONX   6017
4      MANHATTAN   5307
5  STATEN ISLAND   1215

In [5]:
# Look at vehicle types involved
q2 = f"SELECT vehicle_type_code1, count(*) as freq FROM {db}.{table} WHERE vehicle_type_code1 IS NOT NULL GROUP BY vehicle_type_code1 ORDER BY freq DESC LIMIT 5"
res2 = wr.athena.read_sql_query(q2, database=db)
display(res2)

                    vehicle_type_code1   freq
0                                Sedan  23846
1  Station Wagon/Sport Utility Vehicle  17386
2                                 Taxi   1197
3                        Pick-up Truck   1019
4                            Box Truck    866